#!/bin/sh -e

if [ ! -f Squirrel.Mac ]; then
  git submodule init
fi

if [ ! -f .git/modules/Squirrel.Mac/config ]; then
  git submodule update
fi

cd Squirrel.Mac
script/bootstrap

echo "Squirrel is all setup"
